--------------------------------------------------------
-- Archivo creado  - martes-mayo-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence INCREMENT_ID_TARJETA_CREDITO
--------------------------------------------------------

   CREATE SEQUENCE  "EMPRESAXYZ"."INCREMENT_ID_TARJETA_CREDITO"  MINVALUE 3 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 8 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence INCREMENTO_ID_CLIENTE
--------------------------------------------------------

   CREATE SEQUENCE  "EMPRESAXYZ"."INCREMENTO_ID_CLIENTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 94 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "EMPRESAXYZ"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(150 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CEDULA_CIUDADANIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TARJETA_CREDITO
--------------------------------------------------------

  CREATE TABLE "EMPRESAXYZ"."TARJETA_CREDITO" 
   (	"ID_TARJETA_CREDITO" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CODIGO" NUMBER, 
	"FECHA_VENCIMIENTO" DATE, 
	"ID_CLIENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into EMPRESAXYZ.CLIENTE
SET DEFINE OFF;

REM INSERTING into EMPRESAXYZ.TARJETA_CREDITO
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPRESAXYZ"."CLIENTE_PK" ON "EMPRESAXYZ"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TARJETA_CREDITO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPRESAXYZ"."TARJETA_CREDITO_PK" ON "EMPRESAXYZ"."TARJETA_CREDITO" ("ID_TARJETA_CREDITO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRG_ID_CLIENTE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EMPRESAXYZ"."TRG_ID_CLIENTE" 
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
SELECT INCREMENTO_ID_CLIENTE.NEXTVAL INTO:NEW.ID_CLIENTE FROM DUAL;
END;
/
ALTER TRIGGER "EMPRESAXYZ"."TRG_ID_CLIENTE" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ID_TARJETA_CREDITO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EMPRESAXYZ"."TRG_ID_TARJETA_CREDITO" 
BEFORE INSERT ON TARJETA_CREDITO
FOR EACH ROW
BEGIN
SELECT INCREMENT_ID_TARJETA_CREDITO.NEXTVAL INTO:NEW.ID_TARJETA_CREDITO FROM DUAL;
END;
/
ALTER TRIGGER "EMPRESAXYZ"."TRG_ID_TARJETA_CREDITO" ENABLE;
--------------------------------------------------------
--  Constraints for Table TARJETA_CREDITO
--------------------------------------------------------

  ALTER TABLE "EMPRESAXYZ"."TARJETA_CREDITO" ADD CONSTRAINT "TARJETA_CREDITO_PK" PRIMARY KEY ("ID_TARJETA_CREDITO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMPRESAXYZ"."TARJETA_CREDITO" MODIFY ("ID_TARJETA_CREDITO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "EMPRESAXYZ"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EMPRESAXYZ"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TARJETA_CREDITO
--------------------------------------------------------

  ALTER TABLE "EMPRESAXYZ"."TARJETA_CREDITO" ADD CONSTRAINT "FK_TARJETA_CREDITO" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "EMPRESAXYZ"."CLIENTE" ("ID_CLIENTE") ENABLE;
